include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    library_private_types_in_public_api: false
    sort_pub_dependencies: false
    no_leading_underscores_for_local_identifiers: true
    unnecessary_to_list_in_spreads: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    prefer_constructors_over_static_methods: false